export type {
  Point,
  DiagramType,
  DiagramMetadata,
  DiagramNode,
  DiagramEdge,
  DiagramContainer,
  DiagramModel,
  DiagramOperation,
  StoredModel,
  VersionEntry,
  ProjectInfo,
  ValidationResult,
  FixResult,
  RecallResult,
  NotationName,
  NotationShape,
  NotationStyleTemplates,
  NotationColourPalette,
  NotationLayoutConventions,
  NotationDefinition,
  ImageAnalysisOptions,
  ScopeClassification,
  ConcernScope,
} from './diagram.js';
